import {ReactNode} from 'react';
import type {Metadata} from 'next';
import React from 'react'; // ReactNode 타입 임포트
import './globals.css';

export const metadata: Metadata = {
  title: 'Happy Birthday',
  description: 'Generated by create next app',
};

export default function RootLayout({children}: {children: ReactNode}) {
  return (
    <html lang='en'>
      <body className='mt-20'>
        <header className='font-bold text-3xl text-center text-red-500'>
          Treasure Hunt
        </header>
        {children} {/* 여기에 자식 페이지들이 렌더링됨 */}
      </body>
    </html>
  );
}
